name = "llamademo"
main = "src/index.js"
compatibility_date = "2024-10-07"
compatibility_flags = ["nodejs_compat"]

[triggers]
# daily at 9am
crons = ["0 9 * * *"]

[ai]
binding = "AI"

[vars]
userEmail = "youremail@example.com"
researcherEmail = "The email to send from. Configure this first in the CF admin under Email Routing"

[[d1_databases]]
binding = "DB"
database_name = "researcher"
database_id = "your database id"

[[send_email]]
name = "EMAIL"
destination_address = "youremail@example.com"
